import { useState } from "react";
import { Save } from "lucide-react";
import toast from "react-hot-toast";
import Button from "../shared/ui/Button";
import Card from "../shared/ui/Card";

export default function ParametrosPage(){
 const [company,setCompany]=useState("JR Proteção Veicular"),[email,setEmail]=useState("financeiro@empresa.com.br"),[due,setDue]=useState(true),[overdue,setOverdue]=useState(true),[auto,setAuto]=useState(false);
 return <div className="space-y-5"><div><p className="text-sm text-gray-500">Configuração do ERP</p><h1 className="mt-1 text-2xl font-bold text-gray-900">Parâmetros</h1></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><div className="space-y-6 xl:col-span-2"><Card title="Empresa" description="Informações básicas utilizadas pelo sistema"><div className="grid grid-cols-1 gap-4 p-5 md:grid-cols-2"><div className="md:col-span-2"><label className="block text-sm font-medium text-gray-700 mb-1.5">Razão social</label><input value={company} onChange={e=>setCompany(e.target.value)} className="h-10 w-full rounded-lg border border-gray-300 px-3 text-sm"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1.5">E-mail financeiro</label><input value={email} onChange={e=>setEmail(e.target.value)} className="h-10 w-full rounded-lg border border-gray-300 px-3 text-sm"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1.5">Moeda</label><input value="BRL - Real Brasileiro" disabled className="h-10 w-full rounded-lg border border-gray-200 bg-gray-50 px-3 text-sm"/></div></div></Card><Card title="Notificações"><div className="divide-y divide-gray-100"><Toggle title="Lembrete de vencimento" value={due} onChange={setDue}/><Toggle title="Alerta de inadimplência" value={overdue} onChange={setOverdue}/><Toggle title="Conciliação automática" value={auto} onChange={setAuto}/></div></Card></div><Card title="Sistema"><div className="space-y-4 p-5"><p className="text-sm font-medium">FinERP</p><p className="text-xs text-gray-500">Versão MVP 1.0.0</p><p className="text-xs leading-5 text-gray-500">Os dados são persistidos localmente no navegador usando Zustand persist.</p></div></Card></div><div className="flex justify-end"><Button onClick={()=>toast.success("Parâmetros salvos com sucesso.")}><Save size={17}/>Salvar parâmetros</Button></div></div>;
}
function Toggle({title,value,onChange}:{title:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between p-5"><p className="text-sm font-medium text-gray-900">{title}</p><button type="button" role="switch" aria-checked={value} onClick={()=>onChange(!value)} className={`relative h-6 w-11 rounded-full ${value?"bg-blue-600":"bg-gray-300"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${value?"left-6":"left-1"}`}/></button></div>}
